import React from 'react'
import Head from 'next/head'
import { Navbar } from './Navbar'
import { Footer } from './Footer'

export const Layout = ({children}) => {
  return (
    
     <>
      <Head>
        <title>E-commerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='layout'>
      <header>
        <Navbar />
      </header>
      <main className='main-container'>
        {children}
        </main>
        <footer>
          <Footer />
        </footer>
       
      </div>
     </>
  )
}
